// Automatically generated by PRGA's RTL generator
module {{ module.name }} (
    input wire [0:0] cfg_empty,     // empty signal of the previous FIFO
    input wire [0:0] cfg_full,      // full signal of the next FIFO
    output reg [0:0] cfg_e,        // configuration enable
    );

    always @* begin
        cfg_e = ~cfg_empty && cfg_full;
    end

endmodule

