// Automatically generated by PRGA's RTL generator
module {{ module.name }} (
    {%- set comma = joiner(",") %}
    {%- for port in itervalues(module.ports) %}{{ comma() }}
    {{ port.direction.case('input', 'output') }} wire [{{ port.width - 1}}:0] {{ port.name }}
    {%- endfor %}
    );
endmodule

