// Automatically generated by PRGA's RTL generator
module fraclut6 (
    // user-accessible ports
    input wire [5:0] in,
    output reg [0:0] o6,
    output reg [0:0] o5,

    // config ports
    input wire [0:0] cfg_clk,
    input wire [0:0] cfg_e,
    input wire [0:0] cfg_we,
    input wire [0:0] cfg_i,
    output wire [0:0] cfg_o
    );

    // mode enum
    localparam MODE_LUT6 = 1'd0;
    localparam MODE_LUT5X2 = 1'd1;

    // prog bits
    reg [63:0] data;
    reg [0:0] mode;

    // lut5 output
    reg [1:0] internal_lut5;
    {%- for i in range(2) %}
    always @* begin
        case (in[4:0])  // synopsys infer_mux
            {%- for j in range(32) %}
            32'd{{ j }}: begin
                internal_lut5[{{ i }}] = data[{{ 32 * i + j }}];
            end
            {%- endfor %}
        endcase
    end
    {%- endfor %}

    // lut6 and lut5
    always @* begin
        o5 = internal_lut5[1];
        case (mode)             // synopsys infer_mux
            MODE_LUT5X2: begin
                o6 = internal_lut5[0];
            end
            MODE_LUT6: begin
                case (in[5])    // synopsys infer_mux
                    1'b0: begin
                        o6 = internal_lut5[0];
                    end
                    1'b1: begin
                        o6 = internal_lut5[1];
                    end
                endcase
            end
        endcase
    end

    always @(posedge cfg_clk) begin
        if (cfg_e && cfg_we) begin    // configuring
            {mode, data} <= {mode, data, cfg_i};
        end
    end

    assign cfg_o = mode[0];

endmodule
