// Automatically generated by PRGA's RTL generator
module prga_clkdiv #(
    parameter   COUNTER_WIDTH = 8
) (
    input wire [0:0]                    clk,
    input wire [0:0]                    rst,

    input wire [COUNTER_WIDTH - 1:0]    div_factor_i,
    input wire [0:0]                    div_factor_we_i,

    output reg [COUNTER_WIDTH - 1:0]    div_factor_o,
    output reg [0:0]                    divclk
    );

    reg [COUNTER_WIDTH - 1:0] divclk_cnt;

    // synopsys translate_off
    initial begin
        divclk = 'b0;
    end
    // synopsys translate_on

    always @(posedge clk) begin
        if (divclk_cnt == 0) begin  // makes sure divclk runs during reset
            divclk <= ~divclk;
        end
    end

    always @(posedge clk) begin
        if (rst) begin
            divclk_cnt <= 'b0;
        end else if (divclk_cnt == 0) begin
            divclk_cnt <= div_factor_o;
        end else begin
            divclk_cnt <= divclk_cnt - 1;
        end
    end

    always @(posedge clk) begin
        if (rst) begin
            div_factor_o <= 'b0;
        end else if (div_factor_we_i) begin
            div_factor_o <= div_factor_i;
        end
    end

endmodule
