// Automatically generated by PRGA's RTL generator
module prga_app_softreg_hsr_ofifo #(
    parameter   DATA_WIDTH  = 32
    , parameter RSTVAL = 32'd0
    , parameter OPT_THRUPUT = 0
) (
    input wire                          clk
    , input wire                        rst_n

    // -- system-side --------------------------------------------------------
    // -- active sync --
    , output reg                        sync_vld
    , input wire                        sync_rdy
    , output reg [DATA_WIDTH - 1:0]     sync_data

    // -- kernel-side --------------------------------------------------------
    , input wire [DATA_WIDTH - 1:0]     var_i
    , input wire                        var_wr
    , output wire                       var_full
    );

    always @(posedge clk) begin
        if (~rst_n) begin
            sync_vld <= 1'b0;
            sync_data <= RSTVAL;
        end else if (var_wr && !var_full) begin
            sync_vld <= 1'b1;
            sync_data <= var_i;
        end else if (sync_rdy) begin
            sync_vld <= 1'b0;
        end
    end

    generate if (OPT_THRUPUT) begin
        assign var_full = sync_vld && !sync_rdy;
    end else begin
        assign var_full = sync_vld;
    end endgenerate

endmodule
