// Automatically generated by PRGA's RTL generator
module prga_fifo_wrbuf #(
    parameter   REGISTERED = 1
    , parameter DECOUPLED = 0
    , parameter DATA_WIDTH = 32
) (
    input wire                          clk
    , input wire                        rst_n

    , output wire                       full_o
    , input wire                        wr_i
    , input wire [DATA_WIDTH - 1:0]     data_i

    , input wire                        full_i
    , output wire                       wr_o
    , output wire [DATA_WIDTH - 1:0]    data_o
    );

    wire buf_rdy_o;

    prga_valrdy_buf #(
        .REGISTERED     (REGISTERED)
        ,.DECOUPLED     (DECOUPLED)
        ,.DATA_WIDTH    (DATA_WIDTH)
    ) i_buf (
        .clk            (clk)
        ,.rst           (~rst_n)         
        ,.rdy_o         (buf_rdy_o)
        ,.val_i         (wr_i)
        ,.data_i        (data_i)
        ,.rdy_i         (~full_i)
        ,.val_o         (wr_o)
        ,.data_o        (data_o)
        );

    assign full_i = ~buf_rdy_o;

endmodule
