// Automatically generated by PRGA's RTL generator
{% set cfg_width = module.ports.cfg_i|length -%}
`timescale 1ns/1ps
module {{ module.name }} (
    input wire [0:0] outpad,
    input wire [0:0] _ipin,
    output reg [0:0] inpad,
    output reg [0:0] _opin,
    output reg [0:0] _oe,

    input wire [0:0] cfg_clk,
    input wire [0:0] cfg_e,
    input wire [0:0] cfg_we,
    input wire [{{ cfg_width - 1 }}:0] cfg_i,
    output wire [{{ cfg_width - 1 }}:0] cfg_o
    );

    wire [{{ module.cfg_bitcount - 1 }}:0] cfg_d;

    always @* begin
        if (cfg_e) begin
            inpad = 1'b0;
            _opin = 1'b0;
            _oe = 1'b0;
        end else begin
            if (cfg_d[0]) begin
                inpad = _ipin;
            end else begin
                inpad = 1'b0;
            end

            if (cfg_d[1]) begin
                _opin = outpad;
                _oe = 1'b1;
            end else begin
                _opin = 1'b0;
                _oe = 1'b0;
            end
        end
    end

    {{ module.instances.i_cfg_data.model.name }} i_cfg_data (
        .cfg_clk            (cfg_clk)
        ,.cfg_e             (cfg_e)
        ,.cfg_we            (cfg_we)
        ,.cfg_i             (cfg_i)
        ,.cfg_o             (cfg_o)
        ,.cfg_d             (cfg_d)
        );

endmodule
