{%- from 'macros/module.tmpl' import instantiation -%}
// Automatically generated by PRGA's RTL generator
`timescale 1ns/1ps
`include "prga_utils.vh"
module {{ module.name }} #(
    parameter   ADDR_WIDTH = {{ module.ports.waddr|length }}
    , parameter DATA_WIDTH = {{ module.ports.din|length }}
    , parameter PROG_ADDR_WIDTH = {{ module.ports.prog_addr|length }}
    , parameter PROG_DATA_WIDTH = {{ module.ports.prog_din|length }}
) (
    input wire clk

    , input wire we
    , input wire [ADDR_WIDTH - 1:0] waddr
    , input wire [DATA_WIDTH - 1:0] din

    , input wire [ADDR_WIDTH - 1:0] raddr
    , output wire [DATA_WIDTH - 1:0] dout

    , input wire prog_clk
    , input wire prog_rst
    , input wire prog_done
    , input wire [PROG_ADDR_WIDTH - 1:0] prog_addr
    , input wire [PROG_DATA_WIDTH - 1:0] prog_din
    , input wire prog_ce
    , input wire prog_we
    , output wire [PROG_DATA_WIDTH - 1:0] prog_dout
    );

    // memory core
    wire                        ip_clk, ip_rst, ip_we, ip_re;
    wire [ADDR_WIDTH - 1:0]     ip_waddr, ip_raddr;
    wire [DATA_WIDTH - 1:0]     ip_din, ip_bw, ip_dout;

    // internal memory
    {{ instantiation(module.instances.i_ram) }} (
        .clk                    (ip_clk)
        ,.rst                   (ip_rst)
        ,.we                    (ip_we)
        ,.waddr                 (ip_waddr)
        ,.din                   (ip_din)
        ,.bw                    (ip_bw)
        ,.re                    (ip_re)
        ,.raddr                 (ip_raddr)
        ,.dout                  (ip_dout)
        );

    // programming ctrl
    {{ instantiation(module.instances.i_init) }} (
        .u_clk                  (clk)
        ,.u_we                  (we)
        ,.u_waddr               (waddr)
        ,.u_din                 (din)
        ,.u_bw                  ({ DATA_WIDTH {1'b1} })
        ,.u_re                  (1'b1)
        ,.u_raddr               (raddr)
        ,.u_dout                (dout)

        ,.prog_clk              (prog_clk)
        ,.prog_rst              (prog_rst)
        ,.prog_done             (prog_done)
        ,.prog_addr             (prog_addr)
        ,.prog_din              (prog_din)
        ,.prog_ce               (prog_ce)
        ,.prog_we               (prog_we)
        ,.prog_dout             (prog_dout)
            
        ,.ip_clk                (ip_clk)
        ,.ip_rst                (ip_rst)
        ,.ip_we                 (ip_we)
        ,.ip_waddr              (ip_waddr)
        ,.ip_din                (ip_din)
        ,.ip_bw                 (ip_bw)
        ,.ip_re                 (ip_re)
        ,.ip_raddr              (ip_raddr)
        ,.ip_dout               (ip_dout)
        );

endmodule
