// Automatically generated by PRGA's blackbox library generator
`timescale 1ns/1ps
module {{ module.vpr_model }} #(
    parameter   ENABLE_CE = 1'b0
) (
    input wire C
    , input wire D
    , input wire E
    , output reg Q
    );

    initial begin
        Q = $unsigned($random) % 2;
    end

    always @(posedge C) begin
        if (~ENABLE_CE || E) begin
            Q <= D;
        end
    end

endmodule
