// Automatically generated by PRGA's RTL generator
module {{ module.name }} (
    input wire [0:0] C
    , input wire [0:0] E
    , input wire [0:0] D
    , output reg [0:0] Q

    , input wire [0:0] prog_done    // programming finished
    , input wire [1:0] prog_data
        // prog_data[0 +: 1] mode: enabled (not disabled)
        //          [1 +: 2] FF ENABLE_CE
    );

    always @(posedge C) begin
        if (~prog_done || ~prog_data[0]) begin
            Q <= 1'b0;
        end else if (~prog_data[1] || E) begin
            Q <= D;
        end
    end

endmodule
