// Automatically generated by PRGA's RTL generator
`timescale 1ns/1ps
module {{ module.name }} (
    input wire [0:0] outpad
    , output reg [0:0] inpad

    , input wire [0:0] ipin
    , output reg [0:0] opin
    , output reg [0:0] oe

    , input wire [0:0] prog_done    // programming
    , input wire [1:0] prog_data    // mode:
                                    //  - 00: disabled
                                    //  - 01: input mode
                                    //  - 10: output mode
    );

    localparam  MODE_INPUT      = 2'h1,
                MODE_OUTPUT     = 2'h2;

    always @* begin
        inpad = 1'b0;
        opin = 1'b0;
        oe = 1'b0;

        if (prog_done) begin
            case (prog_data)
                MODE_INPUT: begin
                    inpad = ipin;
                end
                MODE_OUTPUT: begin
                    opin = outpad;
                    oe = 1'b1;
                end
            endcase
        end
    end

endmodule
