// Automatically generated by PRGA's RTL generator
module {{ module.name }} (
    input wire [0:0] outpad

    , output reg [0:0] opin

    , input wire [0:0] prog_done    // programming
    , input wire [0:0] prog_data    // mode: enabled (not disabled)
    );

    always @* begin
        if (~prog_done || ~prog_data) begin
            opin = 1'b0;
        end else begin
            opin = outpad;
        end
    end

endmodule
