// Automatically generated by PRGA's RTL generator
`timescale 1ns/1ps
module {{ module.name }} (
    input wire [0:0] outpad

    , output reg [0:0] opin

    , input wire [0:0] cfg_e    // programming
    , input wire [0:0] prim_e   // this primitive is enabled in app-emulation
    );

    always @* begin
        if (cfg_e || ~prim_e) begin
            opin = 1'b0;
        end else begin
            opin = outpad;
        end
    end

endmodule
