// Automatically generated by PRGA's RTL generator
module prga_app_softreg_const #(
    parameter   DATA_WIDTH  = 32
    , parameter RSTVAL      = 0
) (
    input wire                          clk
    , input wire                        rst_n

    // -- system-side --------------------------------------------------------
    // -- request --
    , output wire                       req_rdy
    , input wire                        req_vld
    , input wire                        req_we
    , input wire [DATA_WIDTH - 1:0]     req_wmask
    , input wire [DATA_WIDTH - 1:0]     req_data

    // -- response --
    , input wire                        resp_rdy
    , output wire                       resp_vld
    , output wire [DATA_WIDTH - 1:0]    resp_data

    // -- kernel-side --------------------------------------------------------
    , output wire [DATA_WIDTH - 1:0]    var_o
    );

    assign var_o = RSTVAL;
    assign req_rdy = 1'b1;  // always ready
    assign resp_vld = 1'b1; // always valid
    assign resp_data = RSTVAL;

endmodule
