// Automatically generated by PRGA's RTL generator
`timescale 1ns/1ps
module {{ module.name }} (
    {%- set portcomma = joiner(",") %}
    {%- for port in itervalues(module.ports) %}{{ portcomma() }}
    {{ port.direction.case('input', 'output') }} wire [{{ port|length - 1}}:0] {{ port.name }}
    {%- endfor %}
    );


    {% for instance in itervalues(module.instances) %}
        {%- for pin in itervalues(instance.pins) %}
            {%- if pin.model.direction.is_output %}
    wire [{{ pin|length - 1 }}:0] _{{ instance.name }}__{{ pin.model.name }};
            {%- endif %}
        {%- endfor %}
    {%- endfor %}
    {% for instance in itervalues(module.instances) %}
    {{ instance.model.name }} {{ instance.name }} (
        {%- set pincomma = joiner(",") %}
        {%- for pin in itervalues(instance.pins) %}{{ pincomma() }}
            {%- if pin.model.direction.is_input %}
        .{{ pin.model.name }}({{ source2verilog(pin) }})
            {%- else %}
        .{{ pin.model.name }}(_{{ instance.name }}__{{ pin.model.name }})
            {%- endif %}
        {%- endfor %}
        );
    {%- endfor %}
    {% for port in itervalues(module.ports) %}
        {%- if port.direction.is_output %}
    assign {{ port.name }} = {{ source2verilog(port)|default("{}'bx".format(port|length), true) }};
        {%- endif %}
    {%- endfor %}

endmodule

