{%- from 'macros/module.tmpl' import instantiation -%}
// Automatically generated by PRGA's RTL generator
`timescale 1ns/1ps
module {{ module.name }} (
    input wire clk

    , input wire we
    , input wire [{{ module.ports.waddr|length - 1 }}:0] waddr
    , input wire [{{ module.ports.din|length - 1 }}:0] din

    , input wire [{{ module.ports.raddr|length - 1 }}:0] raddr
    , output wire [{{ module.ports.dout|length - 1 }}:0] dout

    , input wire prog_done
    );

    {{ instantiation(module.instances.i_ram) }} (
        .clk                    (clk)
        ,.rst                   (~prog_done)
        ,.we                    (we)
        ,.waddr                 (waddr)
        ,.din                   (din)
        ,.bw                    ({ {{ module.ports.din|length }} {1'b1} })
        ,.re                    (prog_done)
        ,.raddr                 (raddr)
        ,.dout                  (dout)
        );

endmodule
